# Generated by Django 4.1.6 on 2023-03-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='accounts.profile')),
            ],
        ),
    ]
